spring:
  application:
    name: give-me-features
  profiles:
    default: local
  devtools:
    livereload:
      enabled: true
gg:
  jte:
    templateLocation: src/main/kte
    templateSuffix: .kte
    use-precompiled-templates: true